on: [push]

name: Tests

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install root project dependencies
        run: npm install
      - name: Build and run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test